version: '3.8'
services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      # Hostname for the n8n instance
      N8N_HOST: "localhost"
      # Public URL for webhooks and UI
      # WEB_URL: "http://192.168.100.113:5678"
      N8N_SECURE_COOKIE: "false"

volumes:
  n8n_data:
    driver: local
